server {
    listen 80 default_server;
    listen [::]:80 default_server;
    # Remplacez dymawonder.fr par votre domaine :
    return 301 https://docker-dyma.online$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    http2 on;

    # Remplacez dymawonder.fr par votre domaine :
    ssl_certificate /certs/fullchain.cer;
    ssl_certificate_key /certs/docker-dyma.online.key;


    # Remplacez dymawonder.fr par votre nom de domaine :
    server_name docker-dyma.online www.docker-dyma.online;
    # Remplacez symfony-chapitre21-mise-en-production par le nom du répertoire de votre projet :
    root /app/public;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index.php(/|$) {
        fastcgi_pass fpm:9000;
        fastcgi_split_path_info ^(.+.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }

    location ~ .php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}


# [Mon Mar 30 16:21:11 UTC 2026] Your cert is in: /root/.acme.sh/docker-dyma.online_ecc/docker-dyma.online.cer
# [Mon Mar 30 16:21:11 UTC 2026] Your cert key is in: /root/.acme.sh/docker-dyma.online_ecc/docker-dyma.online.key
# [Mon Mar 30 16:21:11 UTC 2026] The intermediate CA cert is in: /root/.acme.sh/docker-dyma.online_ecc/ca.cer
# [Mon Mar 30 16:21:11 UTC 2026] And the full-chain cert is in: /root/.acme.sh/docker-dyma.online_ecc/fullchain.cer